# Generated by Django 6.0.1 on 2026-02-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='chroma_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
